const data = {
  products: [
    {
      _id: '1',
      name: 'Aloe Jelly',
      category: 'Beauty',
      image: '/images/aloe-jelly.png',
      price: 11.99,
      countInStock: 10,
      brand: 'Unknown',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Aloe Soap',
      category: 'Beauty',
      image: '/images/aloe-soap.png',
      price: 1.99,
      countInStock: 10,
      brand: 'Unknown',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Bose Waterproof Speaker',
      category: 'Beauty',
      image: '/images/bose-waterproof-speaker.png',
      price: 99.99,
      countInStock: 10,
      brand: 'Unknown',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Derma Sunscreen',
      category: 'Beauty',
      image: '/images/derma-sunscreen.png',
      price: 20.99,
      countInStock: 10,
      brand: 'Unknown',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Digital Air Fryer',
      category: 'Beauty',
      image: '/images/digital-air-fryer.png',
      price: 69.99,
      countInStock: 10,
      brand: 'Unknown',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Dutchman Honey',
      category: 'Beauty',
      image: '/images/dutchman-honey.png',
      price: 17.99,
      countInStock: 0,
      brand: 'Unknown',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;